version: '3'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    networks:
    - mean-network
  frontend:
    build:
      context: ./frontend
    ports:
    - "8081:8081"
    networks:
    - mean-network
  
  mongo:
    image: mongo:latest
    networks: 
    - mean-network

networks: 
  mean-network:
    driver: bridge 
   
    
    
